config/routes.rb
ChatMunoh::Application.routes.draw do
  resources :munohs do
    resources :phrases
  end

  resources :rooms do
    resources :talks
  end
  match "/auth/:provider/callback" => "sessions#create"
  match "/signout" => "sessions#destroy", :as => :signout
  root :to => "sessions#new"
end

app/models/munoh.rb
class Munoh < ActiveRecord::Base
  attr_accessible :name, :twitter_name, :phrases_attributes

  has_many :rooms
  has_many :phrases

  validates_presence_of :name

  before_save :try_to_get_valid_response

  def valid_twitter_name?
    self.twitter_name && self.twitter_name_changed?
  end

  def try_to_get_valid_response
    return nil unless valid_twitter_name?
    retrieve_phrases_on_timeline
    self.phrases.each(&:save)
  rescue Twitter::Error::TooManyRequests, Twitter::Error::NotFound, Twitter::Error::Forbidden
    self.twitter_name = self.twitter_name_was
  end

  def retrieve_phrases_on_timeline
    twitter_client = MyTwitterClient.new(self.twitter_name)
    twitter_client.user_timeline.each do |tweet|
      self.phrases.build(keyword: tweet["keyword"], reply: tweet["reply"])
    end
  end
end

app/models/my_twitter_client.rb
class MyTwitterClient
  def initialize(twitter_name)
    @twitter_name = twitter_name
    @twitter = Twitter.configure do |config|
      config.consumer_key = ENV["TWITTER_KEY"]
      config.consumer_secret = ENV["TWITTER_SECRET"]
      config.oauth_token = ENV["OAUTH_TOKEN"]
      config.oauth_token_secret = ENV["OAUTH_TOKEN_SECRET"]
    end
  end

  def user_timeline
    timeline = Array.new
    @twitter.user_timeline(@twitter_name).each do|tweet|
      keyword = find_source_tweet(tweet.in_reply_to_status_id)
      reply = format_reply(find_source_owner(tweet.in_reply_to_user_id), tweet.text)
      timeline << {"keyword" => keyword, "reply" => reply}
    end
    timeline
  end

  def status(tweet_id)
    @twitter.status(tweet_id)
  end

  def user(user_id)
    @twitter.user(user_id)
  end

  def find_source_tweet(tweet_id)
    return unless tweet_id
    keyword = @twitter.status(tweet_id).text
    remove_noise(keyword)
  rescue Twitter::Error::NotFound, Twitter::Error::Forbidden
    nil
  end

  def find_source_owner(user_id)
    @twitter.user(user_id).name
  rescue Twitter::Error::NotFound, Twitter::Error::Forbidden
    nil
  end

  def format_reply(user_name, reply)
    if user_name
      reply.gsub! user_name, "[user_name]"
    end
    remove_noise(reply)
  end

  def remove_noise(text)
    if text
      text.gsub! /@[\S]+[\s]*/, ""
      text.gsub! %r|http://[\S]*[\s]*|, ""
    end
    text
  end
end

app/models/phrase.rb
class Phrase < ActiveRecord::Base
  attr_accessible :keyword, :reply, :munoh_id

  belongs_to :munoh

  validates_presence_of :reply
end

app/models/room.rb
class Room < ActiveRecord::Base
  attr_accessible :title, :user_id, :munoh_id

  belongs_to :owner, class_name: "User", foreign_key: :user_id
  has_many :talks
  has_many :active_users, source: :user, through: :talks, 
    conditions: proc { ['talks.created_at >= ?', 5.minutes.ago]} 
  belongs_to :munoh

  validates_presence_of :title

  scope :in_the_room, lambda { |room| where(room_id: room.id) }

  def owner?(current_user)
    owner.to_param == current_user.to_param
  end
end

app/models/talk.rb
class Talk < ActiveRecord::Base
  attr_accessible :log, :room_id, :user_id

  belongs_to :room
  belongs_to :user

  validates_presence_of :room_id
  validates_presence_of :user_id

  scope :in_the_room, lambda { |room_id| where(room_id: room_id) }

  def owner?(current_user)
    user.to_param == current_user.to_param
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_presence_of :provider
  validates_presence_of :uid
  validates_presence_of :name

  attr_accessible :name, :provider, :uid

  has_many :rooms
  has_many :talks

  def self.create_with_omniauth(auth)
    create do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
    end
  end
end

app/controllers/application_controller.rb
class Forbidden < StandardError; end
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user
  before_filter :login_required

  rescue_from Forbidden do |e|
    redirect_to root_path, :alert => 'Access denied.'
  end

  private
  def login_required
    raise Forbidden unless user?
  end

  def user?
    @_user ||= User.find(session[:user_id]) if session[:user_id]
  rescue ActiveRecord::RecordNotFound
    nil
  end

  def current_user
    @_current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/munohs_controller.rb
class MunohsController < ApplicationController
  before_filter :find_munoh, only: [:edit, :update, :destroy]

  def index
    @munohs = Munoh.all
  end

  def new
    @munoh = Munoh.new
  end

  def create
    @munoh = Munoh.new(params[:munoh])
    if @munoh.save
      redirect_to munohs_url
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @munoh.update_attributes(params[:munoh])
      redirect_to munohs_url
    else
      render :edit
    end
  end

  def destroy
    @munoh.destroy
    redirect_to munohs_url
  end

  private
  def find_munoh
    @munoh = Munoh.find(params[:id])
  end  
end

app/controllers/phrases_controller.rb
class PhrasesController < ApplicationController
  before_filter :find_munoh
  before_filter :find_phrase, only: [:update, :destroy]

  def index
    @phrases = @munoh.phrases
  end

  def new
    @phrase = @munoh.phrases.new
  end

  def edit
    @phrase = Phrase.find(params[:id])
  end

  def create
    @phrase = @munoh.phrases.new(params[:phrase])
    if @phrase.save
      redirect_to munoh_phrases_url
    else
      render :new
    end
  end

  def update
    if @phrase.update_attributes(params[:phrase])
      redirect_to munoh_phrases_url
    else
      render :edit
    end
  end

  def destroy
    @phrase.destroy
    redirect_to munoh_phrases_url
  end

  private
  def find_munoh
    @munoh = Munoh.find_by_id(params[:munoh_id])
    unless @munoh
      redirect_to munohs_url
      return false
    end
  end

  def find_phrase
    @phrase = @munoh.phrases.find(params[:id])
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_filter :find_room, only: [:edit, :update, :destroy]
  before_filter :list_munohs, only: [:new, :edit]

  def index
    @rooms = Room.all
  end

  def new
    @room = current_user.rooms.build
  end

  def create
    @room = current_user.rooms.build(params[:room])
    if @room.save
      redirect_to rooms_url
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @room.update_attributes(params[:room])
      redirect_to rooms_url
    else
      render :edit
    end
  end

  def destroy
    @room.destroy
    redirect_to rooms_url
  end

  private
  def find_room
    @room = current_user.rooms.find(params[:id])
  end

  def list_munohs
    @munohs = Munoh.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :login_required

  def create
    auth = request.env["omniauth.auth"]
    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
    if user.valid?
      session[:user_id] = user.id
      redirect_to rooms_url, :notice => "Signed in!"
    else
      redirect_to root_url, :alert => "Can not Login"
    end 
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Signed out!"
  end

  def new
  end
end

app/controllers/talks_controller.rb
class TalksController < ApplicationController
  def index
    @talks = Talk.where(room_id: params[:room_id])
    @new_talk = current_user.talks.build(room_id: params[:room_id])
    @active_users = Room.find(params[:room_id]).active_users
  end

  def create
    @talk = current_user.talks.build(params[:talk])
    if @talk.save
      redirect_to room_talks_url
    else
      redirect_to room_talks_url
    end
  end
  
  def destroy
    @talk = current_user.talks.in_the_room(params[:room_id]).find(params[:id])
    @talk.destroy

    redirect_to room_talks_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/phrases_helper.rb
module PhrasesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/talks_helper.rb
module TalksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ChatMunoh</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/munohs/_form.html.haml
=form_for(munoh) do |f|
  = render partial: 'shared/errors', locals: {model: munoh}
  .field
    =f.label :name
    =f.text_field :name
  .field
    =f.label :twitter_name
    =f.text_field :twitter_name
  .actions
    =f.submit nil

app/views/munohs/edit.html.haml
=render partial: 'form', locals: {munoh: @munoh}

app/views/munohs/index.html.haml
.munoh-list
  %table{border: 1}
    -@munohs.each do |munoh|
      %tr
        %td.munoh-name= link_to munoh.name, munoh_path(munoh)
        %td.munoh-phrases= link_to "Phrases", munoh_phrases_path(munoh)
        %td.munoh-action #{link_to  "Edit", edit_munoh_path(munoh)} | | 
          #{ link_to "Delete", munoh_path(munoh), method: :delete, confirm: 'Are you sure?' } | 
.new-munoh
  =link_to "New", new_munoh_path

app/views/munohs/new.html.haml
=render partial: 'form', locals: {munoh: @munoh}

app/views/phrases/_form.html.haml
=form_for [munoh, phrase] do |f|
  = render partial: 'shared/errors', locals: {model: phrase}
  .field
    =f.label :keyword
    =f.text_field :keyword
  .field
    =f.label :reply
    =f.text_field :reply
  .actions
    =f.submit nil

app/views/phrases/edit.html.haml
=render partial: 'form', locals: {munoh: @munoh, phrase: @phrase}

app/views/phrases/index.html.haml
.phrase-list
  %table.phrases
    %tr
      %th.phrase-keyword-title Keyword
      %th.phrase-reply-title Reply
    -@phrases.each do |phrase|
      %tr
        %td.phrase-keyword= phrase.keyword
        %td.phrase-reply= phrase.reply
        %td.phrase-edit= link_to "edit", edit_munoh_phrase_path(munoh_id: phrase.munoh_id, id: phrase.to_param)
        %td.phrase-delete= link_to "delete", munoh_phrase_path(munoh_id: phrase.munoh_id, id: phrase.to_param), method: :delete
.new-phrase
  = link_to "new", new_munoh_phrase_path(munoh_id: @munoh.id)
.back-to-munoh-list
  = link_to "Munoh List", munohs_path

app/views/phrases/new.html.haml
=render partial: 'form', locals: {munoh: @munoh, phrase: @phrase}

app/views/rooms/_form.html.haml
=form_for(room) do |f|
  = render partial: 'shared/errors', locals: {model: room}
  .field
    =f.label :title
    =f.text_field :title
  .field
    =f.label :munoh_id
    =f.select :munoh_id, options_from_collection_for_select(Munoh.all, :id, :name), prompt: "選択してください"
  .actions
    =f.submit nil

app/views/rooms/create.html.haml
%h1 Rooms#create
%p Find me in app/views/rooms/create.html.haml

app/views/rooms/edit.html.haml
=render "form", room: @room

app/views/rooms/index.html.haml
.room-list
  %table{border: 1}
    -@rooms.each do |room|
      %tr
        %td.room-title=link_to room.title, room_talks_path(room_id: room.to_param)
        %td.room-action #{link_to_if  room.owner?(current_user), "Edit", edit_room_path(room)}| |
          #{ link_to_if room.owner?(current_user), "Delete", room_path(room), |
          method: :delete, confirm: 'Are you sure?' } |
.new-room
  =link_to "New", new_room_path

app/views/rooms/new.html.haml
=render "form", room: @room

app/views/shared/_errors.html.haml
-if model.errors.any?
  #error_explanation
    %h2="#{pluralize(model.errors.count, "error")} prohibited this #{model.class} from being saved:"
    %ul
      -model.errors.full_messages.each do |msg|
        %li= msg

app/views/talks/index.html.haml
.talk-list
  -@talks.each do |talk|
    %span.talk-user-name= talk.user.name 
    %span.talk-log= talk.log
    %span.talk-action= link_to_if(talk.owner?(current_user), "x", 
      room_talk_path(talk, room_id: params[:room_id]), method: :delete, confirm: "Are you sure?"){}
    %br
.active-user-list{style: "float: right;"}
  -@active_users.each do |user|
    %span.user-name= user.name
    %br
.send-talk
  = form_for @new_talk, url: {action: :create} do |f|
    = render partial: 'shared/errors', locals: {model: @new_talk}
    = f.hidden_field :room_id
    .field
      = f.label :log
      = f.text_field :log
    .actions
      = f.submit nil
.back-to-room-list
  = link_to "Room List", rooms_path